apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name | quote }}
spec:
  accessModes:
    - {{ .Values.accessMode | quote }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.capacity | quote }}
  storageClassName: {{ .Values.storageClassName | quote }}
  selector:
    matchLabels:
      release: "stable"
    matchExpressions:
      - {key: environment, operator: In, values: [dev]}